SET FOREIGN_KEY_CHECKS = 0;

CREATE SCHEMA IF NOT EXISTS `codegym` DEFAULT CHARACTER SET utf8 ;
USE `codegym` ;

DROP TABLE IF EXISTS `ViTri` ;

CREATE TABLE IF NOT EXISTS `ViTri` (
  `IdVT` INT NOT NULL,
  `TenVT` VARCHAR(45) NOT NULL,
  CONSTRAINT PK_ViTri PRIMARY KEY (`IdVT`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `TrinhDo` ;

CREATE TABLE IF NOT EXISTS `TrinhDo` (
  `IdTD` INT NOT NULL,
  `TrinhDo` VARCHAR(45) NOT NULL,
  CONSTRAINT PK_TrinhDo PRIMARY KEY (`IdTD`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `BoPhan` ;

CREATE TABLE IF NOT EXISTS `BoPhan` (
  `IdBP` INT NOT NULL,
  `TenBP` VARCHAR(45) NOT NULL,
  CONSTRAINT PK_BoPhan PRIMARY KEY (`IdBP`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `NhanVien` ;

CREATE TABLE IF NOT EXISTS `NhanVien` (
  `IdNV` INT NOT NULL,
  `HoTen` VARCHAR(45) NOT NULL,
  `NgaySinh` DATE NOT NULL,
  `SoCMND` INT NOT NULL,
  `SDT` VARCHAR(45) NOT NULL,
  `Luong` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `DiaChi` VARCHAR(45) NOT NULL,
  `ViTri_IdVT` INT NOT NULL,
  `TrinhDo_IdTD` INT NOT NULL,
  `BoPhan_IdBP` INT NOT NULL,
  CONSTRAINT PK_NhanVien PRIMARY KEY (`IdNV`),
  CONSTRAINT FK_NhanVien_ViTri FOREIGN KEY (`ViTri_IdVT`) REFERENCES ViTri(`IdVT`),
  CONSTRAINT FK_NhanVien_TrinhDo FOREIGN KEY (`TrinhDo_IdTD`) REFERENCES TrinhDo(`IdTD`),
  CONSTRAINT FK_NhanVien_BoPhan FOREIGN KEY (`BoPhan_IdBP`) REFERENCES BoPhan(`IdBP`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `DichVuDiKem` ;

CREATE TABLE IF NOT EXISTS `DichVuDiKem` (
  `IdDVDK` INT NOT NULL,
  `TenDVDK` VARCHAR(45) NOT NULL,
  `Gia` INT NOT NULL,
  `DonVi` INT NOT NULL,
  `TrangThaiKhaDung` VARCHAR(45) NOT NULL,
  CONSTRAINT PK_DiVuDiKem PRIMARY KEY (`IdDVDK`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `LoaiKhach` ;

CREATE TABLE IF NOT EXISTS `LoaiKhach` (
  `IdLK` INT NOT NULL,
  `TenLK` VARCHAR(45) NOT NULL,
  CONSTRAINT PK_LoaiKhach PRIMARY KEY (`IdLK`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `KhachHang` ;

CREATE TABLE IF NOT EXISTS `KhachHang` (
  `IdKH` INT NOT NULL,
  `HoTen` VARCHAR(45) NOT NULL,
  `NgaySinh` DATE NOT NULL,
  `SoCMND` INT NOT NULL,
  `SDT` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `DiaChi` VARCHAR(255) NOT NULL,
  `LoaiKhach_IdLK` INT NOT NULL,
  CONSTRAINT PK_KhachHang PRIMARY KEY (`IdKH`),
  CONSTRAINT FK_KhachHang_LoaiKhach FOREIGN KEY (`LoaiKhach_IdLK`) REFERENCES LoaiKhach(`IdLK`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `LoaiDichVu` ;

CREATE TABLE IF NOT EXISTS `LoaiDichVu` (
  `IdLDV` INT NOT NULL,
  `TenLDV` VARCHAR(45) NOT NULL,
  CONSTRAINT PK_LoaiDichVu PRIMARY KEY (`IdLDV`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `KieuThue` ;

CREATE TABLE IF NOT EXISTS `KieuThue` (
  `IdKT` INT NOT NULL,
  `TenKT` VARCHAR(45) NOT NULL,
  `GiaThue` INT NOT NULL,
  CONSTRAINT PK_KieuThue PRIMARY KEY (`IdKT`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `DichVu` ;

CREATE TABLE IF NOT EXISTS `DichVu` (
  `IdDV` INT NOT NULL,
  `TenDV` VARCHAR(45) NOT NULL,
  `DienTich` INT NOT NULL,
  `SoTang` INT NOT NULL,
  `SoNguoiToiDa` INT NOT NULL,
  `GiaThue` INT NOT NULL,
  `TrangThai` VARCHAR(45) NOT NULL,
  `LoaiDichVu_IdLDV` INT NOT NULL,
  `KieuThue_IdKT` INT NOT NULL,
  CONSTRAINT PK_DichVu PRIMARY KEY (`IdDV`),
  CONSTRAINT FK_DichVu_LoaiDichVu FOREIGN KEY (`LoaiDichVu_IdLDV`) REFERENCES LoaiDichVu(`IdLDV`),
  CONSTRAINT FK_DichVu_KieuThue FOREIGN KEY (`KieuThue_IdKT`) REFERENCES KieuThue(`IdKT`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `HopDong` ;

CREATE TABLE IF NOT EXISTS `HopDong` (
  `IdHD` INT NOT NULL,
  `NgayLamHD` DATETIME NOT NULL,
  `NgayKetThuc` DATETIME NOT NULL,
  `TienDatCoc` INT NOT NULL,
  `TongTien` INT NOT NULL,
  `NhanVien_IdNV` INT NOT NULL,
  `KhachHang_IdKH` INT NOT NULL,
  `DichVu_IdDV` INT NOT NULL,
  CONSTRAINT PK_HopDong PRIMARY KEY (`IdHD`),
  CONSTRAINT FK_HopDong_NhanVien FOREIGN KEY (`NhanVien_IdNV`) REFERENCES NhanVien(`IdNV`),
  CONSTRAINT FK_HopDong_KhachHang FOREIGN KEY (`KhachHang_IdKH`) REFERENCES KhachHang(`IdKH`),
  CONSTRAINT FK_HopDong_DichVu FOREIGN KEY (`DichVu_IdDV`) REFERENCES DichVu(`IdDV`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `HopDongChiTiet` ;

CREATE TABLE IF NOT EXISTS `HopDongChiTiet` (
  `IdHDCT` INT NOT NULL,
  `SoLuong` INT NOT NULL,
  `DichVuDiKem_IdDVDK` INT NOT NULL,
  `HopDong_IdHD` INT NOT NULL,
  CONSTRAINT PK_HopDongChiTiet PRIMARY KEY (`IdHDCT`),
  CONSTRAINT FK_HopDongChiTiet_DichVuDiKem FOREIGN KEY (`DichVuDiKem_IdDVDK`) REFERENCES DichVuDiKem(`IdDVDK`),
  CONSTRAINT FK_HopDongChiTiet_HopDong FOREIGN KEY (`HopDong_IdHD`) REFERENCES HopDong(`IdHD`))
ENGINE = InnoDB;

SET FOREIGN_KEY_CHECKS = 1;